name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up Core
      run: go install ./cmd/core && core setup

    - name: "Install video dependencies (TODO: move to a command)"
      run: sudo add-apt-repository ppa:savoury1/ffmpeg4 && sudo apt install libswscale-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev libasound2-dev

    - name: Build
      run: go build -v ./...

    # we can't test vgpu, xyz, and system on the ci since there is no vulkan support
    - name: Test
      run: go test -v $(go list ./... | grep -v vgpu | grep -v xyz | grep -v system) -coverprofile cover.out

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: cover.out
      if: github.event_name == 'push'
